mindbox-moscow/ui-kit

- images.d.ts
- package.json
- src/images.d.ts
- webpack.config.js
- yarn.lock
> [RFC] [issue-138] Добавлена возможность использования SVG в качестве компонентов

- src/SelectMulti/SelectMulti.md
- src/SelectMulti/SelectMulti.scss
- src/SelectMulti/SelectMulti.tsx
- src/SelectMulti/index.ts
> [RFC] [issue-132] Добавлен компонент SelectMulti

- src/Input/Input.scss
- src/Input/Input.tsx
- src/SelectNested/SelectNested.scss
- src/SelectNested/SelectNested.tsx
- Для компонента `Input` добавлен пропс `size`, который на данный момент принимает только значение `small` и делает инпут соответственно маленького размера.
- Этот маленький инпут теперь используется в компоненте `SelectNested`
> Модифицированы компоненты Input  и SelectNested

- src/SelectMulti/SelectMulti.scss
> [RFC] [issue-163] UI-кит: Пофиксил отображение дропдауна у SelectMulti 

- src/SelectMulti/SelectMulti.scss
> [RFC] [issue-163] Добавил border-radius к родительскому контенеру

- src/SelectNested/SelectNested.scss
> [RFC] [issue-164] UI-кит: Отрефакторил отображение дропдауна у SelectNested

- examples/MainActive.tsx
- examples/What.tsx
- examples/When.tsx
- src/DateField/DateField.md
- src/DateField/DateField.scss
- src/DateField/DateField.tsx
- src/TimeField/TimeField.md
- src/TimeField/TimeField.scss
- src/TimeField/TimeField.tsx
> [RFC] [issue-187] Added noShadow props for all simple input-components

- src/FilterWrapper/FilterWrapper.md
- src/FilterWrapper/FilterWrapper.scss
- src/FilterWrapper/FilterWrapper.tsx
* Remove filter wrapper width
* Pass caption for "clear" button
> Fix FilterWrapper

- src/FiltrationGroupComponent/FiltrationGroupComponent.md
- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
- src/FiltrationGroupComponent/FiltrationGroupComponent.tsx
https://github.com/mindbox-moscow/ui-kit/issues/272
Исправлено поведение соединения скобок, добавлена функция для вычисления позиции "И"/"Или"
> [RFC] [issue-272] Ситуация 1: Скобка соединяет конкретные условия фильтрации. Пример 3 

- src/FiltrationGroupComponent/FiltrationGroupComponent.md
- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
- src/FiltrationGroupComponent/FiltrationGroupComponent.tsx
https://github.com/mindbox-moscow/ui-kit/issues/273
https://github.com/mindbox-moscow/ui-kit/issues/274
Измнено формирование соединений, изменено поведение label, добавлено соединение груп условий по макету
[feature-issue-273.mindbox.csssr.ru](feature-issue-273.mindbox.csssr.ru)
> [RFC] [issue-273] Ситуация 2: Скобка соединяет группы условий. Пример 1

- src/FiltrationConditionComponent/FiltrationConditionComponent.tsx
- src/FiltrationGroupComponent/FiltrationGroupComponent.md
- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
- src/FiltrationGroupComponent/FiltrationGroupComponent.tsx
Исправлены баги
https://github.com/mindbox-moscow/ui-kit/issues/297
[feature-issue-297.mindbox.csssr.ru](http://feature-issue-297.mindbox.csssr.ru/)
> [RFC][issue-297] Ещё несколько багов вложенных групп

- src/FilterConditionSelector/FilterConditionSelector.md
- src/FilterConditionSelector/FilterConditionSelector.tsx
- src/FilterConditionSelector/FilterConditionSelectorItem.tsx
- src/FilterConditionSelector/index.ts
Без этого трудно подружить с Redux
> Вынес рендер детей в FiltrationConditionSelector

- src/FilterWrapper/FilterWrapper.md
- src/FilterWrapper/FilterWrapper.scss
- src/FiltrationConditionComponent/FiltrationConditionComponent.scss
- src/FiltrationConditionComponent/FiltrationConditionComponent.tsx
- src/FiltrationConditionComponent/types.ts
- src/FiltrationGroupComponent/FiltrationGroupComponent.md
- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
- src/FiltrationGroupComponent/FiltrationGroupComponent.tsx
https://github.com/mindbox-moscow/ui-kit/issues/303
[http://feature-issue-303.mindbox.csssr.ru/](http://feature-issue-303.mindbox.csssr.ru/)
> [RFC][issue-303] Ховер над простым фильтром

- src/FilterWrapper/FilterWrapper.scss
> [RFC] [issue-330] Фикс ширины FilterWrapper

- src/ActionsDropdown/ActionsDropdown.scss
- src/Button/Button.scss
- src/DetalizationBlockInfo/DetalizationBlockInfo.scss
- src/DetalizationHeader/DetalizationHeader.scss
- src/FilterConditionEditorButton/FilterConditionEditorButton.scss
- src/FilterConditionEditorComponent/FilterConditionEditorComponent.scss
- src/FilterDetails/FilterDetails.scss
- src/FilterWrapper/FilterWrapper.scss
- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
- src/Module/Module.scss
- src/Page/Page.scss
- src/SectionWrapper/SectionWrapper.scss
- src/SelectNested/SelectNested.scss
- src/TextLine/TextLine.scss
- src/TimeField/TimeField.scss
> [RFC] [issue-343] Delete outline for buttons and links

- src/FilterConditionPopup/FilterConditionPopup.tsx
- src/FilterConditionPopup/types.ts
- src/FiltrationGroupComponent/FiltrationGroupComponent.tsx
https://github.com/mindbox-moscow/ui-kit/issues/304
[http://feature-issue-304.mindbox.csssr.ru/](http://feature-issue-304.mindbox.csssr.ru/)
> [RFC][issue-304] Простой фильтр в режиме редактирования

- src/Button/Button.scss
- src/Button/Button.tsx
- src/FilterConditionEditorButton/FilterConditionEditorButton.scss
- src/FiltrationGroupComponent/FiltrationGroupComponent.md
- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
- src/FiltrationGroupComponent/FiltrationGroupComponent.tsx
Исправлена минимальная высота условия
> [RFC][issue-376] Несколько багов в отображении групп

- src/FilterWrapper/FilterWrapper.scss
- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
https://github.com/mindbox-moscow/ui-kit/issues/384
> [RFC][issue-384]Отсутствуют отступы внутри FilterWrapper

- src/FilterWrapper/FilterWrapper.md
- src/FiltrationConditionComponent/FiltrationConditionComponent.scss
- src/FiltrationConditionComponent/FiltrationConditionComponent.tsx
https://github.com/mindbox-moscow/ui-kit/issues/385
[http://feature-issue-385.mindbox.csssr.ru/](http://feature-issue-385.mindbox.csssr.ru/)
> [RFC][issue-385]Баг с затемнением простого условия

- src/FilterWrapper/FilterWrapper.md
- src/FiltrationConditionComponent/types.ts
- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
- src/FiltrationGroupComponent/FiltrationGroupComponent.tsx
https://github.com/mindbox-moscow/ui-kit/issues/376
[http://feature-issue-376.mindbox.csssr.ru/](http://feature-issue-376.mindbox.csssr.ru/)
> [RFC][issue-376]Несколько багов в отображении групп

- src/FilterWrapper/FilterWrapper.md
- src/FilterWrapper/FilterWrapper.scss
- src/FilterWrapper/FilterWrapper.tsx
- src/FilterWrapper/types.ts
https://github.com/mindbox-moscow/ui-kit/issues/337
[http://feature-issue-337.mindbox.csssr.ru/](http://feature-issue-337.mindbox.csssr.ru/)
> [RFC][issue-337]FilterWrapper: отображение количества выбранных элементов

- src/FilterWrapper/FilterWrapper.scss
- src/FiltrationConditionComponent/FiltrationConditionComponent.scss
- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
- src/FiltrationGroupComponent/FiltrationGroupComponent.tsx
https://github.com/mindbox-moscow/ui-kit/issues/338
[http://feature-issue-338.mindbox.csssr.ru/](http://feature-issue-338.mindbox.csssr.ru/)
> [RFC][issue-338]Увеличить площадь ховеров

- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
https://github.com/mindbox-moscow/ui-kit/issues/385
> [RFC][issue-385]Баг с затенением простого условия

- src/FilterConditionEditorButton/FilterConditionEditorButton.md
- src/FilterConditionSelector/FilterConditionSelector.scss
- src/FilterConditionSelector/FilterConditionSelectorItem.tsx
https://github.com/mindbox-moscow/ui-kit/issues/401
[http://feature-issue-401.mindbox.csssr.ru/](http://feature-issue-401.mindbox.csssr.ru/)
> [RFC][issue-401]Сквозной поиск в меню

- src/BlockComponents/components/GridColumn/GridColumn.scss
- src/FilterWrapper/FilterWrapper.md
- src/Tooltip/Tooltip.scss
https://github.com/mindbox-moscow/ui-kit/issues/365
Исправлены баги
> [RFC][issue-365]Ошибки валидации в фильтрах

- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
- styleguide.config.js
https://github.com/mindbox-moscow/ui-kit/issues/404
> [RFC][issue-404]Разный шрифт на Windows и MacOS

- src/FilterWrapper/FilterWrapper.scss
https://github.com/mindbox-moscow/ui-kit/issues/422
[http://feature-issue-422.mindbox.csssr.ru/](http://feature-issue-422.mindbox.csssr.ru/)
> [RFC][issue-422]Косметические изменения в FilterWrapper.

- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
https://github.com/mindbox-moscow/ui-kit/issues/404
[http://feature-issue-404.mindbox.csssr.ru/](http://feature-issue-404.mindbox.csssr.ru/)
> [RFC][issue-404]Баг: разный шрифт на Windows и MacOS

- src/FilterWrapper/FilterWrapper.scss
- src/FilterWrapper/FilterWrapper.tsx
https://github.com/mindbox-moscow/ui-kit/issues/437
[http://feature-issue-437.mindbox.csssr.ru/](http://feature-issue-437.mindbox.csssr.ru/)
> [RFC][issue-437]Убрать большой отступ сверху

- src/FiltrationConditionComponent/FiltrationConditionComponent.scss
- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
- src/SegmentButtonExpand/SegmentButtonExpand.scss
https://github.com/mindbox-moscow/ui-kit/issues/434
[http://feature-issue-434.mindbox.csssr.ru/](http://feature-issue-434.mindbox.csssr.ru/)
> [RFC][issue-434]Сегмент фильтра

- src/FilterConditionSelector/FilterConditionSelector.tsx
- src/FilterConditionSelector/types.ts
- src/FiltrationConditionComponent/FiltrationConditionComponent.tsx
- src/FiltrationConditionComponent/types.ts
https://github.com/mindbox-moscow/ui-kit/issues/438
> [RFC][issue-438]Не работает крестик в меню

- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
- src/FiltrationGroupComponent/FiltrationGroupComponent.tsx
https://github.com/mindbox-moscow/ui-kit/issues/444
> [RFC][issue-444]Ховер в группе должен захватывать крестик

- src/FilterWrapper/FilterWrapper.md
- src/FilterWrapper/FilterWrapper.scss
- src/FilterWrapper/FilterWrapper.tsx
https://github.com/mindbox-moscow/ui-kit/issues/449
[http://feature-issue-449.mindbox.csssr.ru/](http://feature-issue-449.mindbox.csssr.ru/)
> [RFC][issue-449]Показывать число выбранных при пустом фильтре

- src/FilterConditionEditorButton/FilterConditionEditorButton.md
- src/FilterConditionEditorButton/FilterConditionEditorButton.scss
- src/FilterConditionEditorButton/FilterConditionEditorButton.tsx
- src/FilterConditionSelector/FilterConditionSelector.scss
- src/FilterConditionSelector/FilterConditionSelector.tsx
- src/IconSvg/icons/ArrowRight.tsx
- src/IconSvg/icons/Duplicate.tsx
- src/Input/Input.tsx
https://github.com/mindbox-moscow/ui-kit/issues/402
[http://feature-issue-402.mindbox.csssr.ru/](http://feature-issue-402.mindbox.csssr.ru/)
> [RFC][issue-402]Привести меню к виду, как в дизайне

- src/BlockComponents/components/Popover/Popover.scss
- src/BlockComponents/components/Popover/Popover.tsx
- src/BlockComponents/components/Popover/index.ts
- src/BlockComponents/components/index.ts
- src/FilterConditionEditorButton/FilterConditionEditorButton.md
- src/FilterConditionEditorComponent/FilterConditionEditorComponent.scss
- src/FiltrationConditionComponent/FiltrationConditionComponent.scss
https://github.com/mindbox-moscow/ui-kit/issues/370
[http://feature-issue-370.mindbox.csssr.ru/](http://feature-issue-370.mindbox.csssr.ru/)
> [RFC][issue-370]Добавлено редактирование условия по сегменту

- src/Button/Button.scss
- src/FilterConditionEditorButton/FilterConditionEditorButton.md
- src/FilterConditionEditorButton/FilterConditionEditorButton.scss
- src/FilterConditionEditorButton/FilterConditionEditorButton.tsx
- src/FilterConditionEditorComponent/FilterConditionEditorComponent.tsx
- src/FilterConditionSelector/FilterConditionSelector.scss
- src/FilterConditionSelector/FilterConditionSelector.tsx
- src/FilterConditionSelector/FilterConditionSelectorItem.tsx
- src/FilterConditionSelector/types.ts
- src/FilterDetails/FilterDetails.tsx
- src/Input/Input.tsx
https://github.com/mindbox-moscow/ui-kit/issues/416
[http://feature-issue-416.mindbox.csssr.ru/](http://feature-issue-416.mindbox.csssr.ru/)
> [RFC][issue-416] Фильтры: управление с клавиатуры

- src/BlockComponents/components/Popover/Popover.scss
- src/FilterConditionEditorButton/FilterConditionEditorButton.md
https://github.com/mindbox-moscow/ui-kit/issues/370
[http://feature-issue-370.mindbox.csssr.ru/](http://feature-issue-370.mindbox.csssr.ru/)
> [RFC][issue-370]Редактирование условия по сегменту

- src/Button/Button.tsx
- src/FilterConditionEditorButton/FilterConditionEditorButton.md
- src/FilterConditionEditorButton/FilterConditionEditorButton.tsx
- src/FilterConditionEditorButton/types.ts
- src/FilterConditionEditorComponent/FilterConditionEditorComponent.tsx
- src/FilterConditionSelector/FilterConditionSelector.scss
- src/FilterConditionSelector/FilterConditionSelector.tsx
- src/FilterConditionSelector/FilterConditionSelectorItem.tsx
- src/FilterDetails/FilterDetails.scss
- src/FilterDetails/FilterDetails.tsx
- src/Input/Input.tsx
https://github.com/mindbox-moscow/ui-kit/issues/416
[http://feature-issue-416.mindbox.csssr.ru/](http://feature-issue-416.mindbox.csssr.ru/)
> [RFC][issue-416]Фильтры: управление с клавиатуры

- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
https://github.com/mindbox-moscow/ui-kit/issues/446
[http://feature-issue-446.mindbox.csssr.ru/](http://feature-issue-446.mindbox.csssr.ru/)
> [RFC][issue-446]Шрифт и спейсинг в лейбле "и/или"

- src/Button/Button.scss
- src/FilterConditionEditorButton/FilterConditionEditorButton.scss
- src/FilterWrapper/FilterWrapper.md
- src/FilterWrapper/FilterWrapper.scss
- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
https://github.com/mindbox-moscow/ui-kit/issues/458
[http://feature-issue-458.mindbox.csssr.ru/](http://feature-issue-458.mindbox.csssr.ru/)
> [RFC][issue-458]Новая итерация дизайна (от 16.10)

- src/FiltrationGroupComponent/FiltrationGroupComponent.md
- src/FiltrationGroupComponent/components/HorizontalBracket/HorizontalBracket.tsx
https://github.com/mindbox-moscow/ui-kit/issues/464
[http://feature-issue-464.mindbox.csssr.ru/](http://feature-issue-464.mindbox.csssr.ru/)
> [RFC][issue-464]Баги с брекетами

- src/FlatSelector/FlatSelector.md
- src/FlatSelector/FlatSelector.scss
- src/FlatSelector/FlatSelector.tsx
- src/FlatSelector/index.ts
- src/FlatSelector/types.ts
https://github.com/mindbox-moscow/ui-kit/issues/409
[http://feature-issue-409.mindbox.csssr.ru/](http://feature-issue-409.mindbox.csssr.ru/)
> [RFC][issue-409]Контрол с 2мя табами

- src/FiltrationGroupComponent/FiltrationGroupComponent.tsx
Будет переделано поведение в дальнейшем
Сейчас закрываем баг
> Отмена скрытия при нажатии вовне для FiltrationGroupComponent

- src/Tooltip/Tooltip.scss
- src/Tooltip/Tooltip.tsx
https://github.com/mindbox-moscow/ui-kit/issues/460
[http://feature-issue-460.mindbox.csssr.ru/](http://feature-issue-460.mindbox.csssr.ru/)
> [RFC][issue-460]Поповер валидации обрезается границей контролла фильтра

- src/FilterConditionEditorButton/FilterConditionEditorButton.tsx
Добавлен callback на получение ссылки на кнопку в FilterConditionEditorButton
> Добавлен callback на получение ссылки на кнопку

- src/ActionFilter/ActionFilter.tsx
- src/FilterConditionSelector/FilterConditionSelector.tsx
- src/FilterConditionSelector/types.ts
- src/Input/Input.tsx
- src/PromotionGroupEdit/PromotionGroupEdit.tsx
- src/SelectNested/SelectNested.tsx
add notFoundMessage for FilterConditionSelector
> use value instead defaultValue

- src/FilterWrapper/FilterWrapper.md
- src/FilterWrapper/FilterWrapper.scss
- src/FiltrationConditionComponent/FiltrationConditionComponent.tsx
- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
- src/FiltrationGroupComponent/FiltrationGroupComponent.tsx
- src/Page/Page.scss
- src/Tooltip/Tooltip.tsx
https://github.com/mindbox-moscow/ui-kit/issues/477
[http://feature-issue-477.mindbox.csssr.ru/](http://feature-issue-477.mindbox.csssr.ru/)
Исправлено отображение лейблов
> [RFC][issue-477]Контрол группы перекрывает всё

- src/FilterConditionEditorButton/FilterConditionEditorButton.md
- src/FilterConditionSelector/FilterConditionSelector.scss
https://github.com/mindbox-moscow/ui-kit/issues/502
[http://feature-issue-502.mindbox.csssr.ru/](http://feature-issue-502.mindbox.csssr.ru/)
> [RFC][issue-502]Фильтр со вложенностью в меню + иконка

- src/FilterWrapper/FilterWrapper.md
- src/FilterWrapper/FilterWrapper.tsx
- src/FilterWrapper/types.ts
https://github.com/mindbox-moscow/ui-kit/issues/339
[http://feature-issue-339.mindbox.csssr.ru/](http://feature-issue-339.mindbox.csssr.ru/)
> [RFC][issue-339]Скролл на списке

- src/WindowClickListener/WindowClickListener.ts
(закрытие OverflowVisibleContainer)
> Залечено реагирование на клик по jQuery.datepicker в WindowClickListener

- src/FilterWrapper/FilterWrapper.scss
https://github.com/mindbox-moscow/ui-kit/issues/546
[http://feature-issue-546.mindbox.csssr.ru/](http://feature-issue-546.mindbox.csssr.ru/)
> [RFC][issue-546]Группа ИЛИ в режиме просмотра не даёт перевести себя в режим редактирования

- src/Page/Page.scss
https://github.com/mindbox-moscow/ui-kit/issues/550
[http://feature-issue-550.mindbox.csssr.ru/](http://feature-issue-550.mindbox.csssr.ru/)
> [RFC][issue-550]Одинаковый скролл для разных платформ

- src/FiltrationConditionComponent/FiltrationConditionComponent.scss
- src/FiltrationConditionComponent/FiltrationConditionComponent.tsx
- src/SegmentButtonExpand/SegmentButtonExpand.scss
- src/SegmentButtonExpand/SegmentButtonExpand.tsx
https://github.com/mindbox-moscow/ui-kit/issues/558
http://feature-issue-558.mindbox.csssr.ru/
> [RFC][issue-558]Проблемы с редактированием сегментов

- src/FilterConditionEditorButton/FilterConditionEditorButton.scss
- src/FilterConditionEditorButton/FilterConditionEditorButton.tsx
- src/FilterWrapper/FilterWrapper.tsx
- src/FilterWrapper/FilterWrapperContext.tsx
- src/FilterWrapper/index.ts
- src/FilterWrapper/types.ts
https://github.com/mindbox-moscow/ui-kit/issues/509
http://feature-issue-509.mindbox.csssr.ru/
> [RFC][issue-509]Схлопывать меню при скролле

- src/FilterWrapper/FilterWrapper.scss
- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
https://github.com/mindbox-moscow/ui-kit/issues/560
http://feature-issue-560.mindbox.csssr.ru/
> [RFC][issue-560]Не работает кнопка переключения типа группы, когда в группе нет условий.

- src/FilterWrapper/FilterWrapper.md
- src/FiltrationConditionComponent/FiltrationConditionComponent.tsx
- src/FiltrationGroupComponent/FiltrationGroupComponent.tsx
- src/FiltrationGroupComponent/FiltrationGroupComponentContext.tsx
- src/FiltrationGroupComponent/index.ts
https://github.com/mindbox-moscow/ui-kit/issues/563
http://feature-issue-558.mindbox.csssr.ru/
> [RFC][issue-563]Ещё баги с брекетами

- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
https://github.com/mindbox-moscow/ui-kit/issues/510
http://feature-issue-510.mindbox.csssr.ru/
> [RFC][issue-510]Выделять вложенные брекеты 1го уровня

- src/FiltrationConditionComponent/FiltrationConditionComponent.scss
https://github.com/mindbox-moscow/ui-kit/issues/529
http://feature-issue-529.mindbox.csssr.ru/
> [RFC][issue-529]Кнопки удаления/дублирования без маусовера

- src/FilterWrapper/FilterWrapper.md
- src/FilterWrapper/FilterWrapper.scss
- src/FilterWrapper/FilterWrapper.tsx
- src/FilterWrapper/types.ts
https://github.com/mindbox-moscow/ui-kit/issues/577
http://feature-issue-577.mindbox.csssr.ru/
> [RFC][issue-577]Не добавляет фильтр в середине страницы

- src/FilterConditionSelector/FilterConditionSelector.scss
https://github.com/mindbox-moscow/ui-kit/issues/590
http://feature-issue-590.mindbox.csssr.ru/
> [RFC][issue-590]Поправить уголок в попапе добавления фильтров

- src/FilterConditionSelector/FilterConditionSelector.scss
- src/FilterConditionSelector/FilterConditionSelector.tsx
- src/FilterConditionSelector/FilterConditionSelectorContext.tsx
- src/FilterConditionSelector/FilterConditionSelectorItem.tsx
https://github.com/mindbox-moscow/ui-kit/issues/572
http://feature-issue-572.mindbox.csssr.ru/
> [RFC][issue-572]По enter'у в поиске сбрасывается меню

- src/FilterConditionEditorButton/FilterConditionEditorButton.scss
- src/FilterConditionEditorButton/FilterConditionEditorButton.tsx
- src/FilterWrapper/components/FilterActionsPopover/FilterActionsPopover.scss
- src/FilterWrapper/components/FilterActionsPopover/FilterActionsPopover.tsx
- src/FiltrationConditionComponent/FiltrationConditionComponent.scss
- src/FiltrationConditionComponent/FiltrationConditionComponent.tsx
- src/Page/Page.scss
Все выпадающие окна внутри фильтров вынесены из OverflowVisibleContainer, некоторые компоненты переписаны на функциональные
https://github.com/mindbox-moscow/ui-kit/issues/585
http://feature-issue-585.mindbox.csssr.ru/
> [RFC][issue-585]Убрать схлопывание меню при скролле

- src/FiltrationConditionComponent/FiltrationConditionComponent.scss
- src/SegmentButtonExpand/SegmentButtonExpand.scss
https://github.com/mindbox-moscow/ui-kit/issues/588
http://feature-issue-588.mindbox.csssr.ru/
> [RFC][issue-588]Большое название фильтра смещает кнопки удаления

- src/SelectMulti/SelectMulti.scss
[При выборе статуса появилась пунктирная линия #566](https://github.com/mindbox-moscow/ui-kit/issues/566)
[Если отжать статус, он отображается с тенюшкой #567](https://github.com/mindbox-moscow/ui-kit/issues/567)
> SelectMulti: Убрана тень и пунктирная линия

- src/FilterConditionSelector/FilterConditionSelector.tsx
- src/FilterConditionSelector/FilterConditionSelectorItem.tsx
- src/FilterDetails/FilterDetails.tsx
- src/HOCs/withOutsideClick/withOutsideClick.tsx
https://github.com/mindbox-moscow/ui-kit/issues/549
http://feature-issue-549.mindbox.csssr.ru/
> [RFC][issue-549]Правки управления с клавиатуры

- src/FilterConditionEditorButton/FilterConditionEditorButton.tsx
- src/FilterConditionEditorButton/types.ts
- src/FiltrationGroupComponent/FiltrationGroupComponent.tsx
- src/Page/Page.scss
https://github.com/mindbox-moscow/ui-kit/issues/609
http://feature-issue-609.mindbox.csssr.ru/
> [RFC][issue-609]Несколько багов

- src/FilterWrapper/components/FilterActionsPopover/FilterActionsPopover.tsx
- src/HOCs/withOutsideClick/withOutsideClick.tsx
Исправил баг в меню, при выборе пункта меню закрывалось окно
+ баг встретил на фронте, что в filterAction передается null, добавил проверку
> Правка еще некоторых багов

- package.json
- postcss.config.js
- src/FilterConditionEditorButton/FilterConditionEditorButton.tsx
- src/FilterConditionSelector/FilterConditionSelector.tsx
- src/FilterDetails/FilterDetails.scss
- src/FilterWrapper/components/FilterActionsPopover/FilterActionsPopover.tsx
- src/FiltrationConditionComponent/FiltrationConditionComponent.scss
- src/FiltrationConditionComponent/FiltrationConditionComponent.tsx
- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
- src/FiltrationGroupComponent/FiltrationGroupComponent.tsx
- src/HOCs/withOutsideClick/withOutsideClick.tsx
- src/OverflowVisibleContainer/OverflowVisibleContainer.tsx
- src/Tooltip/Tooltip.tsx
1. Исправлен HOC
2. Из OverflowVisibleContainer убрал HOC, чтобы лиснеры не распространялись на тултипы
> Правки багов

- package.json
- src/FilterConditionSelector/FilterConditionSelector.tsx
- yarn.lock
https://github.com/mindbox-moscow/ui-kit/issues/640
http://feature-issue-640.mindbox.csssr.ru/
> [RFC][issue-640]Скролл в меню не скроллит всю страницу

- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
https://github.com/mindbox-moscow/ui-kit/issues/637
http://feature-issue-637.mindbox.csssr.ru/
> [RFC][issue-637]Перенести крестик для больших фильтров

- src/FilterConditionSelector/FilterConditionSelector.scss
- src/FilterConditionSelector/FilterConditionSelectorItem.tsx
https://github.com/mindbox-moscow/ui-kit/issues/630
> [RFC][issue-630]В меню съехала иконка раскрытия категории

- src/FilterWrapper/FilterWrapper.scss
- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
https://github.com/mindbox-moscow/ui-kit/issues/644
> [RFC][issue-644]Поправить неактивную кнопку "добавить фильтр"

- src/FilterConditionSelector/FilterConditionSelector.scss
- src/FilterConditionSelector/FilterConditionSelector.tsx
- src/FilterDetails/FilterDetails.tsx
- src/FilterWrapper/FilterWrapper.tsx
- src/FilterWrapper/FilterWrapperContext.tsx
- src/FilterWrapper/index.ts
- src/FilterWrapper/types.ts
- src/HOCs/withOutsideClick/withOutsideClick.tsx
https://github.com/mindbox-moscow/ui-kit/issues/635
> [RFC][issue-635]При скролле меню прилипает кверху

- src/FilterConditionEditorButton/FilterConditionEditorButton.scss
- src/FilterConditionEditorButton/FilterConditionEditorButton.tsx
- src/FilterWrapper/FilterWrapper.md
- src/FilterWrapper/FilterWrapper.scss
- src/FiltrationConditionComponent/FiltrationConditionComponent.scss
- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
- src/FiltrationGroupComponent/FiltrationGroupComponent.tsx
Поправил пропсы minfied на minified
Исправил баг с прозрачностью кнопок
Убрал точку в брекетах
https://github.com/mindbox-moscow/ui-kit/issues/651
> [RFC][issue-651]Лишняя точка в брекете

- src/FilterConditionEditorButton/FilterConditionEditorButton.md
- src/FilterConditionSelector/FilterConditionSelector.tsx
- src/FilterWrapper/FilterWrapper.tsx
- src/FlatSelect/FlatSelect.scss
- src/FlatSelect/FlatSelect.tsx
- src/FlatSelect/components/Dropdown/Dropdown.tsx
- src/FlatSelect/components/Dropdown/DropdownContext.tsx
- src/FlatSelect/components/Dropdown/index.ts
- src/FlatSelect/components/Panel/Panel.tsx
- src/FlatSelect/components/SelectSearchList/SelectSearchList.tsx
- src/FlatSelect/components/SelectSearchList/types.ts
- src/FlatSelect/components/SelectSearchRow/SearchRow.tsx
- src/FlatSelect/components/SelectSearchRow/types.ts
- src/FlatSelect/types.ts
- src/Textbox/Textbox.tsx
- src/Textbox/types.ts
- src/utils/constants.ts
https://github.com/mindbox-moscow/ui-kit/issues/643
> [RFC][issue-643]Поправить selector

- src/SegmentButtonExpand/SegmentButtonExpand.scss
https://github.com/mindbox-moscow/ui-kit/issues/672
> [RFC][issue-667]Не работает кнопка "использовать как фильтр"

- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
https://github.com/mindbox-moscow/ui-kit/issues/679
> [RFC][issue-679]У кнопки "Добавить фильтр" пропало некликабельное состояние

- src/FlatSelect/FlatSelect.scss
- src/FlatSelect/components/Dropdown/Dropdown.tsx
- src/FlatSelect/components/SelectSearchRow/SearchRow.tsx
- src/Textbox/Textbox.tsx
https://github.com/mindbox-moscow/ui-kit/issues/589
> [RFC][issue-589]Выпадающий список вылезает за экран

- src/Input/Input.scss
https://github.com/mindbox-moscow/ui-kit/issues/678
> [RFC][issue-678]Не удаляется текст при нажатии на крестик

- src/FilterConditionEditorButton/FilterConditionEditorButton.md
- src/FilterConditionSelector/FilterConditionSelector.tsx
- src/FilterConditionSelector/FilterConditionSelectorContext.tsx
- src/FilterConditionSelector/FilterConditionSelectorItem.tsx
- src/FilterConditionSelector/utils/index.ts
https://github.com/mindbox-moscow/ui-kit/issues/653
> [RFC][issue-653]Выбрал пункт в меню - курсор в поле ввода

- package.json
- src/FilterDetails/FilterDetails.tsx
- yarn.lock
https://github.com/mindbox-moscow/ui-kit/issues/682
> [RFC][issue-682]Циклический таб при управлении с клавиатуры

- src/IconSvg/IconSvg.md
- src/IconSvg/icons/Link.tsx
- src/IconSvg/icons/index.ts
[Добавляем блоки с вариантами #652](https://github.com/mindbox-moscow/ui-kit/issues/652)
> Просмотр рассылки: Добавить иконку для ссылки

- src/FilterWrapper/FilterWrapper.md
- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
- src/FiltrationGroupComponent/FiltrationGroupComponent.tsx
https://github.com/mindbox-moscow/ui-kit/issues/691
[Пример - FilterWrapper 12.5](http://feature-issue-691.mindbox.csssr.ru/#filterwrapper)
> [RFC][issue-691]Лишний брекет у фильтра внутри сегмента

- src/BlockComponents/components/GridColumn/GridColumn.scss
- src/FlatSelect/FlatSelect.scss
https://github.com/mindbox-moscow/ui-kit/issues/711
> [RFC][issue-711]Большое название вылезает за границы выпадашки

- src/Page/Page.scss
https://github.com/mindbox-moscow/ui-kit/issues/700
> [RFC][issue-700]Баги при добавлении фильтра на странице рассылки

- src/Tooltip/Tooltip.scss
https://github.com/mindbox-moscow/ui-kit/issues/670
> [RFC][issue-670]Заменить тултип на странице промоакций на новый

- src/FilterWrapper/FilterWrapper.tsx
Для этого ПР https://github.com/mindbox-moscow/frontend/pull/1752/files
> Исправлены тесты

- src/OverflowVisibleContainer/OverflowVisibleContainer.scss
- src/Tooltip/Tooltip.scss
[Тултип перекрывает меню при скролле](https://github.com/mindbox-moscow/ui-kit/issues/728)
https://github.com/mindbox-moscow/ui-kit/issues/724
> Фикс для бага с перекрытием меню при скролле

- src/FlatSelect/components/Dropdown/Dropdown.tsx
- src/FlatSelect/components/Dropdown/DropdownContext.tsx
- src/FlatSelect/components/SelectSearchList/SelectSearchList.tsx
https://github.com/mindbox-moscow/ui-kit/issues/730
> [RFC][issue-730]Сломалась кнопка закрыть у выпадающего списка

- src/FilterWrapper/FilterWrapper.scss
https://github.com/mindbox-moscow/ui-kit/issues/715
Сделал каскадом, чтобы не ломать прелоадер в других местах фронта
> [RFC][issue-715]Обрезается прелоадер в блоке фильтров

- src/FlatSelect/components/Dropdown/Dropdown.tsx
- src/FlatSelect/components/SelectSearchRow/SearchRow.tsx
- src/HOCs/withOutsideClick/withOutsideClick.tsx
https://github.com/mindbox-moscow/ui-kit/issues/718
> [RFC][issue-718]Клик вне выпадающего списка не закрывает его

- src/FilterConditionSelector/FilterConditionSelector.scss
- src/FilterConditionSelector/FilterConditionSelector.tsx
- src/FilterConditionSelector/FilterConditionSelectorContext.tsx
- src/FilterConditionSelector/FilterConditionSelectorItem.tsx
https://github.com/mindbox-moscow/ui-kit/issues/719
Исправил обрезание меню
Изменил скрол списка на нативную функцию
> [RFC][issue-719]Меню обрезается снизу на небольшой странице

- src/FilterConditionEditorButton/FilterConditionEditorButton.md
- src/FilterConditionEditorButton/FilterConditionEditorButton.scss
- src/FilterConditionSelector/FilterConditionSelector.scss
- src/FilterConditionSelector/FilterConditionSelector.tsx
- src/utils/constants.ts
- src/utils/helpers.ts
https://github.com/mindbox-moscow/ui-kit/issues/587
Исправил поведение скрола, для сафари оставил старый функционал, для остальных браузеров работает нативный скрол с обработкой css
+ пример для имитации большого кол-ва элементов в списке
> [RFC][issue-587]Тормозит скролл фильтра

- src/FilterConditionSelector/FilterConditionSelector.scss
https://github.com/mindbox-moscow/ui-kit/issues/747
> [RFC][issue-747]Меню растянулось на всю страницу

- src/BlockComponents/components/InvalidHighLight/InvalidHighLight.scss
- src/BlockComponents/components/Wrapper/Wrapper.scss
Исправил выравнивание
Немного подправил компонент подсветки ошибки
https://github.com/mindbox-moscow/ui-kit/issues/739
> [RFC][issue-739]Сломался тултип

- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
- src/FiltrationGroupComponent/FiltrationGroupComponent.tsx
- src/sass/mixins/brackets.scss
Исправлены баги брекетов
https://github.com/mindbox-moscow/ui-kit/issues/751
> [RFC][issue-751]Сломались брекеты во вложенных фильтрах

- src/FilterConditionSelector/FilterConditionSelector.tsx
Добавлено выставление фокуса на поиск при монтировании компонента
https://github.com/mindbox-moscow/ui-kit/issues/654
> [RFC][issue-654]Фокус на поиске при раскрытии меню

- src/ActionsDropdown/ActionsDropdown.md
- src/ActionsDropdown/ActionsDropdown.scss
- src/ActionsDropdown/ActionsDropdown.tsx
- src/ActionsDropdown/components/Action.tsx
- src/ActionsDropdown/components/Dropdown.tsx
- src/ActionsDropdown/components/Group.tsx
- src/ActionsDropdown/components/index.ts
- src/ActionsDropdown/context.ts
- src/Icon/Icon.md
- src/Icon/Icon.scss
- src/Icon/Icon.tsx
- styleguide.config.js
[Меню доп. ссылок по вариантам #656](https://github.com/mindbox-moscow/ui-kit/issues/656)
> Просмотр рассылки: Меню доп. ссылок по вариантам

- src/FilterConditionSelector/FilterConditionSelector.tsx
- src/HOOKs/index.ts
- src/HOOKs/useDebounce/index.ts
- src/HOOKs/useDebounce/useDebounce.tsx
Добавил hook для debounce
Добавил debounce для поиска в меню
https://github.com/mindbox-moscow/ui-kit/issues/763
> [RFC][issue-763]Мини-оптимизация меню

- src/FilterConditionSelector/FilterConditionSelector.scss
Исправил отступы
https://github.com/mindbox-moscow/ui-kit/issues/760
> [RFC][issue-760]Ширина брекетов в меню

- src/FiltrationConditionComponent/FiltrationConditionComponent.scss
https://github.com/mindbox-moscow/ui-kit/issues/767
> [RFC][issue-767]Фильтр внутри сегмента выделен синим

- src/FlatSelect/FlatSelect.scss
https://github.com/mindbox-moscow/ui-kit/issues/765
> [RFC][issue-765]Выпадашка отрисовывается с задержкой

- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
https://github.com/mindbox-moscow/ui-kit/issues/770
> [RFC][issue-770]Сломался фокус у групп

- src/FiltrationConditionComponent/FiltrationConditionComponent.scss
- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
- src/FiltrationGroupComponent/FiltrationGroupComponent.tsx
- src/sass/mixins/brackets.scss
https://github.com/mindbox-moscow/ui-kit/issues/771
> [RFC][issue-771]Брекеты тянутся до след элемента

- examples/MainActive.tsx
- examples/What.tsx
- examples/When.tsx
- src/ConditionEditorPopup/ConditionEditorPopup.tsx
- src/DateField/DateField.md
- src/DateField/DateField.scss
- src/DateField/DateField.tsx
- src/DateField/consts.ts
- src/DateRange/DateRange.md
- src/DateRange/DateRange.scss
- src/DateRange/DateRange.tsx
- src/DateRange/components/InnerEditorComponent/InnerEditorComponent.tsx
- src/DateRange/constants.tsx
- src/DateRange/types.ts
- src/FilterConditionEditorButton/FilterConditionEditorButton.md
- src/FilterWrapper/FilterWrapper.md
- src/RadioButton/RadioButton.tsx
- src/utils/constants.ts
- src/utils/helpers.ts
https://github.com/mindbox-moscow/ui-kit/issues/772
> issue-772 добавил отображение периода и убрал время в DateRange

- src/FilterConditionSelector/FilterConditionSelector.scss
- src/FilterConditionSelector/FilterConditionSelectorItem.tsx
https://github.com/mindbox-moscow/ui-kit/issues/778
> [RFC][issue-778]Баги со скроллом в меню

- src/FiltrationConditionComponent/types.ts
https://github.com/mindbox-moscow/ui-kit/issues/780
> [RFC][issue-780]Выделять красным исключающие режимы

- src/FilterConditionSelector/FilterConditionSelector.tsx
- src/FilterDetails/FilterDetails.tsx
- src/FilterDetails/types.ts
- src/IconSvg/icons/Revert.tsx
https://github.com/mindbox-moscow/ui-kit/issues/795
> [RFC][issue-795]Эскейп не возвращает к выбору на списке

- src/OverflowVisibleContainer/OverflowVisibleContainer.scss
https://github.com/mindbox-moscow/ui-kit/issues/799
> [RFC][issue-799]Сломалась выпадашка на странице проблем

- src/FilterConditionSelector/FilterConditionSelector.scss
- src/FilterConditionSelector/FilterConditionSelector.tsx
https://github.com/mindbox-moscow/ui-kit/issues/808
> [RFC][issue-808]Поменять иконку при поиске

- src/FilterConditionEditorButton/FilterConditionEditorButton.md
- src/FilterWrapper/FilterWrapper.md
- src/FilterWrapper/components/FilterActions/FilterActions.tsx
https://github.com/mindbox-moscow/ui-kit/issues/807
> [RFC][issue-807]Почистить консоль

- src/FilterConditionSelector/FilterConditionSelector.tsx
- src/FilterConditionSelector/utils/index.ts
https://github.com/mindbox-moscow/ui-kit/issues/796
> [RFC][issue-796]Добавление фильтра по enter'у

- src/FilterConditionSelector/FilterConditionSelector.scss
https://github.com/mindbox-moscow/ui-kit/issues/809
> [RFC][issue-809]Меню быстро схлопывается

- src/FlatSelect/FlatSelect.tsx
https://github.com/mindbox-moscow/issues-dev2/issues/27
> https://github.com/mindbox-moscow/issues-dev2/issues/27

- src/FiltrationConditionComponent/FiltrationConditionComponent.scss
https://github.com/mindbox-moscow/ui-kit/issues/837
> [RFC][issue-837]У групп пропал ховер

- src/RadioButton/RadioButton.md
- src/RadioButton/RadioButton.scss
- src/RadioButton/RadioButton.tsx
https://github.com/mindbox-moscow/ui-kit/issues/789
> [issue-789]: disabled состояние для radiobutton

- src/FlatSelect/FlatSelect.md
- src/FlatSelect/FlatSelect.scss
- src/FlatSelect/components/Dropdown/Dropdown.tsx
https://github.com/mindbox-moscow/ui-kit/issues/821
> [RFC][issue-821]Не работает свойство disabled в компоненте FlatSelect

- src/SegmentButtonEdit/SegmentButtonEdit.scss
- src/SegmentButtonExpand/SegmentButtonExpand.scss
https://github.com/mindbox-moscow/ui-kit/issues/836
> [RFC][issue-836]На iOS не отображаются кнопки у сегмента

- src/FilterConditionEditorButton/FilterConditionEditorButton.md
- src/FilterConditionSelector/FilterConditionSelector.tsx
- src/FilterDetails/FilterDetails.tsx
- src/FilterDetails/types.ts
https://github.com/mindbox-moscow/ui-kit/issues/833
> [RFC][issue-833]Скроллится страница вместо меню

- src/DateRange/DateRange.tsx
- src/utils/helpers.ts
https://github.com/mindbox-moscow/ui-kit/issues/790
> [issue-790]: коррекция датапикера под время сервера

- src/FiltrationConditionComponent/FiltrationConditionComponent.scss
- src/FiltrationConditionComponent/FiltrationConditionComponent.tsx
- src/FiltrationConditionComponent/types.ts
https://github.com/mindbox-moscow/ui-kit/issues/780
> issue-780: Выделять красным исключающие

- src/FiltrationConditionComponent/FiltrationConditionComponent.scss
https://github.com/mindbox-moscow/ui-kit/issues/780
> [issue-780]: сделал выделение не жирным

- src/DateRange/DateRange.tsx
https://github.com/mindbox-moscow/ui-kit/issues/790
> [issue-790]: fix dateRange bug

- src/FiltrationConditionComponent/FiltrationConditionComponent.scss
- src/sass/mixins/brackets.scss
https://github.com/mindbox-moscow/ui-kit/issues/832
> [issue-832]: фикс подсветки кнопок

- src/ActionsDropdown/ActionsDropdown.scss
- src/ActionsDropdown/ActionsDropdown.tsx
- src/FilterWrapper/FilterWrapper.md
- src/FiltrationConditionComponent/FiltrationConditionComponent.md
- src/FiltrationConditionComponent/FiltrationConditionComponent.scss
- src/FiltrationConditionComponent/FiltrationConditionComponent.tsx
- src/FiltrationConditionComponent/types.ts
- src/FiltrationGroupComponent/FiltrationGroupComponent.md
- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
- src/FiltrationGroupComponent/FiltrationGroupComponent.tsx
- src/FiltrationGroupComponent/types.ts
https://github.com/mindbox-moscow/ui-kit/issues/792
> [RFC][issue-792]Сделать фильтр группой

- src/FilterConditionSelector/FilterConditionSelector.tsx
https://github.com/mindbox-moscow/ui-kit/issues/869
> [RFC][issue-869]Не работает скролл меню на Safari

- src/FlatSelect/components/Dropdown/Dropdown.tsx
https://github.com/mindbox-moscow/ui-kit/issues/843
Поправил выделение первого пункта, теперь выделяется только во время поиска
> [RFC][issue-843]Баги с выпадающими списками

- src/ActionsDropdown/ActionsDropdown.scss
- src/FilterWrapper/components/FilterActions/FilterActions.scss
- src/SegmentButtonExpand/SegmentButtonExpand.scss
- src/SegmentButtonExpand/SegmentButtonExpand.tsx
- src/SegmentButtonExpand/types.ts
https://github.com/mindbox-moscow/ui-kit/issues/829
> [issue-829]: фикс поповера и кнопок меню

- src/FilterConditionSelector/FilterConditionSelector.scss
- src/FlatSelect/FlatSelect.scss
https://github.com/mindbox-moscow/ui-kit/issues/844
> [RFC][issue-844]Не прокручивается меню при скролле

- src/ActionsDropdown/ActionsDropdown.scss
- src/ActionsDropdown/ActionsDropdown.tsx
- src/FiltrationConditionComponent/FiltrationConditionComponent.scss
- src/FiltrationConditionComponent/FiltrationConditionComponent.tsx
- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
- src/FiltrationGroupComponent/FiltrationGroupComponent.tsx
https://github.com/mindbox-moscow/ui-kit/issues/783
> [issue-783]: фикс выпадашки в кондишинах

- src/ActionsDropdown/ActionsDropdown.scss
- src/FiltrationConditionComponent/FiltrationConditionComponent.scss
- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
https://github.com/mindbox-moscow/ui-kit/issues/783
> issue-783: фикс наползания кнопок

- src/sass/mixins/brackets.scss
https://github.com/mindbox-moscow/ui-kit/issues/871
> [RFC][issue-871]Баги с брекетами

- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
https://github.com/mindbox-moscow/ui-kit/issues/783
> issue-783: фикс наползания "или"

- src/FilterConditionSelector/FilterConditionSelector.scss
- src/FilterConditionSelector/FilterConditionSelectorItem.tsx
https://github.com/mindbox-moscow/ui-kit/issues/831
> [RFC][issue-831]Убрать горизонтальный скролл в меню

- src/FlatSelect/FlatSelect.scss
- src/FlatSelect/components/Dropdown/Dropdown.tsx
https://mindbox.slack.com/archives/C09NTAM2M/p1586441169054300
https://github.com/mindbox-moscow/issues-devx/issues/157
> Fix FlatSelect Dropdown

- src/ActionsDropdown/ActionsDropdown.tsx
https://github.com/mindbox-moscow/ui-kit/issues/886
Часть 1
> [RFC][issue-886]Клик на точки в триггере = 404

- src/FilterWrapper/FilterWrapper.scss
- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
https://github.com/mindbox-moscow/ui-kit/issues/828
> [RFC][issue-828]Клик на "добавить фильтр" не смещает кнопку

- src/FilterConditionSelector/FilterConditionSelector.scss
- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
https://github.com/mindbox-moscow/ui-kit/issues/901
> [RFC][issue-901]Пропадает плашка выбора в меню

- src/HOOKs/index.ts
- src/HOOKs/usePortalContainer/index.ts
- src/HOOKs/usePortalContainer/usePortalContainer.tsx
- src/OverflowVisibleContainer/OverflowVisibleContainer.tsx
- src/Portal/Portal.tsx
- src/Portal/index.ts
Добавлен компонент портала
Добавлен хук для портала
https://github.com/mindbox-moscow/ui-kit/issues/860
Обсуждение: https://github.com/mindbox-moscow/frontend/pull/2209#discussion_r407452223
> [RFC][issue-860]Проверить правильно ли работает скроллирование при большой шапке

- src/FilterWrapper/FilterWrapper.scss
- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
https://github.com/mindbox-moscow/ui-kit/issues/899
> [issue-899]: фикс disabled кнопки в фильтрах

- src/FilterWrapper/FilterWrapper.md
- src/FiltrationConditionComponent/FiltrationConditionComponent.scss
- src/FiltrationConditionComponent/FiltrationConditionComponent.tsx
- src/FiltrationConditionComponent/types.ts
- src/IconSvg/IconSvg.md
- src/IconSvg/icons/Add.tsx
- src/IconSvg/icons/index.ts
- src/sass/variables.scss
https://github.com/mindbox-moscow/ui-kit/issues/900
> [issue-900]: кнопка для добавления кондишна

- src/FilterDetails/FilterDetails.scss
- src/FilterWrapper/FilterWrapper.md
- src/FiltrationConditionComponent/FiltrationConditionComponent.scss
- src/FiltrationConditionComponent/FiltrationConditionComponent.tsx
- src/FiltrationConditionComponent/FiltrationConditionComponentContext.tsx
- src/FiltrationConditionComponent/index.ts
- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
- src/FiltrationGroupComponent/FiltrationGroupComponent.tsx
- src/SegmentButtonExpand/SegmentButtonExpand.tsx
- src/sass/mixins/brackets.scss
https://github.com/mindbox-moscow/ui-kit/issues/890
https://github.com/mindbox-moscow/ui-kit/issues/910
> [RFC][issue-890]Баги с брекетами при вставке

- src/FiltrationConditionComponent/FiltrationConditionComponent.tsx
https://github.com/mindbox-moscow/ui-kit/issues/936
> issue-936: фикс кнопок в сегменте

- src/FilterWrapper/FilterWrapper.md
- src/FilterWrapper/FilterWrapper.tsx
- src/FiltrationConditionComponent/FiltrationConditionComponent.scss
- src/sass/variables.scss
https://github.com/mindbox-moscow/ui-kit/issues/942
> [issue-942]: изменение цвета иконки

- src/FlatSelect/FlatSelect.scss
- src/FlatSelect/components/SelectSearchRow/SearchRow.tsx
https://github.com/mindbox-moscow/ui-kit/issues/945
> [RFC][issue-945]Слишком быстрый скролл в выпадающем списке

- src/FilterWrapper/FilterWrapper.md
- src/FiltrationConditionComponent/FiltrationConditionComponent.scss
- src/FiltrationConditionComponent/FiltrationConditionComponent.tsx
https://github.com/mindbox-moscow/ui-kit/issues/953
> [RFC][issue-953]Исправить баги отображения фильтов

- src/Button/Button.scss
https://github.com/mindbox-moscow/ui-kit/issues/946
> [RFC][issue-946]Нельзя добавить "группу или" на корневом уровне

- src/FilterConditionEditorButton/FilterConditionEditorButton.tsx
- src/HOOKs/useClickOutside/useClickOutside.tsx
https://github.com/mindbox-moscow/ui-kit/issues/948
> [RFC][issue-948]Сломалось добавление следующего фильтра по enter

- src/BlockComponents/components/Wrapper/Wrapper.scss
- src/BlockComponents/components/Wrapper/Wrapper.tsx
- src/FilterDetails/FilterDetails.scss
- src/FiltrationConditionComponent/FiltrationConditionComponent.scss
- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
- src/sass/mixins/brackets.scss
https://github.com/mindbox-moscow/ui-kit/issues/956
Добавлены нативные пробелы  вместо марджина
Исправлено еще несколько багов
> [RFC][issue-956]Склеиваются "равен + текст" в фильтре

- src/FilterConditionSelector/FilterConditionSelectorItem.tsx
https://github.com/mindbox-moscow/ui-kit/issues/931
> [RFC][issue-931]Пропадает содержимое фильтра при клике на название

- src/FilterConditionSelector/FilterConditionSelector.scss
- src/FilterConditionSelector/FilterConditionSelector.tsx
https://github.com/mindbox-moscow/ui-kit/issues/967
> [RFC][issue-967]Вернуть треугольник в поиск

- src/FlatSelect/FlatSelect.scss
- src/FlatSelect/components/Dropdown/Dropdown.tsx
- src/FlatSelect/components/Dropdown/DropdownContext.tsx
- src/FlatSelect/components/Search/Search.tsx
- src/FlatSelect/components/SelectSearchRow/SearchRow.tsx
https://github.com/mindbox-moscow/ui-kit/issues/916
> [RFC][issue-916]Перемещение в выпадашке режима двигает меню

- src/BlockComponents/components/Wrapper/Wrapper.scss
- src/FiltrationConditionComponent/FiltrationConditionComponent.scss
- src/FiltrationConditionComponent/FiltrationConditionComponent.tsx
- src/FiltrationConditionComponent/types.ts
- src/IconSvg/IconSvg.scss
- src/SegmentButtonExpand/SegmentButtonExpand.scss
- src/SegmentButtonExpand/SegmentButtonExpand.tsx
https://github.com/mindbox-moscow/ui-kit/issues/969
> [RFC][issue-969]Съехала верстка

- src/FilterWrapper/FilterWrapper.scss
- src/FilterWrapper/FilterWrapper.tsx
https://github.com/mindbox-moscow/ui-kit/issues/902
> [RFC][issue-902]У FilterWrapper торчат углы

- src/FilterConditionSelector/FilterConditionSelector.tsx
- src/FilterConditionSelector/FilterConditionSelectorContext.tsx
- src/FilterConditionSelector/FilterConditionSelectorItem.tsx
Не работает переход с клавиатуры на полях вида перечисление #905
Не работал выбор элемента в списке, когда элемент находился в свернутой группе
> [RFC][issue-905]Не работает переход с клавиатуры на полях вида перечисление

- src/FilterConditionSelector/FilterConditionSelector.tsx
- src/Input/Input.scss
Удалил функционал выбора пункта по нажатию на Enter
#983
> [RFC][issue-983]Убрать автовыбор при поиске

- src/FilterWrapper/FilterWrapper.scss
- src/FiltrationConditionComponent/FiltrationConditionComponent.scss
- src/FiltrationConditionComponent/FiltrationConditionComponent.tsx
- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
- src/FiltrationGroupComponent/FiltrationGroupComponent.tsx
- src/sass/mixins/brackets.scss
Ховер справа у условий #973
Брекет виден сквозь плашку #980
> [RFC][issue-973]Ховер справа у условий

- src/FiltrationConditionComponent/FiltrationConditionComponent.scss
- src/FiltrationConditionComponent/FiltrationConditionComponent.tsx
Настроить пробелы во FiltrationConditionComponent #988
> [RFC][issue-988]Настроить пробелы во FiltrationConditionComponent

- src/FilterWrapper/FilterWrapper.scss
> [RFC][issue-991]Убрать затенение количества на списке

- src/FilterWrapper/FilterWrapper.md
- src/FiltrationConditionComponent/FiltrationConditionComponent.scss
- src/FiltrationConditionComponent/FiltrationConditionComponent.tsx
Перенести иконку добавления фильтра влево #952
> [RFC][issue-952]Перенести иконку добавления фильтра влево

- src/FlatSelect/FlatSelect.scss
> [RFC][issue-917]Выпадашки не схлопываются при клике во вне

- package.json
- src/FlatSelect/components/Dropdown/Dropdown.tsx
- src/FlatSelect/components/Panel/Panel.tsx
- src/Tooltip/Tooltip.tsx
- yarn.lock
Фильтр категории не влезает во вьюпорт #960
Выпадашка по системному имени не влезает в экран #981
> [RFC][issue-960]Фильтр категории не влезает во вьюпорт

- src/FilterWrapper/FilterWrapper.scss
> [RFC][issue-994]При редактировании фильтра в сегменте просвечивают галки

- src/BlockComponents/components/Wrapper/Wrapper.scss
- src/FiltrationConditionComponent/FiltrationConditionComponent.scss
- src/SegmentButtonExpand/SegmentButtonExpand.scss
> [RFC][issue-1000]Строка с фильтром отображается не ровно

- src/FiltrationConditionComponent/FiltrationConditionComponent.scss
- src/FiltrationConditionComponent/FiltrationConditionComponent.tsx
- src/FiltrationConditionComponent/types.ts
- src/FiltrationGroupComponent/types.ts
https://github.com/mindbox-moscow/issues-dev2/issues/185
> Добавлен режим отображения "notApplicable" для условия фильтрации.

- src/FiltrationGroupComponent/FiltrationGroupComponent.tsx
https://github.com/mindbox-moscow/issues-dev2/issues/185
> Добавлен режим отображения "notApplicable" для группы с условиями фильтрации. В таком режиме не доступны действия над группой.

- src/Tooltip/Tooltip.scss
- src/Tooltip/Tooltip.tsx
> [RFC][issue-1004]Поправить иконку с валидацией

- src/FlatSelect/FlatSelect.scss
> [RFC][issue-1010]На странице шагов триггера появилась лесенка

- src/OverflowVisibleContainer/OverflowVisibleContainer.tsx
> [RFC][issue-1025]Селект открывается с неправильным позиционированием

- src/__tests__/FlatSelect.test.tsx
Добавлен тест на срабатывание функции hide() вызванной через ref
#955
> [RFC][issue-955]Выпадашка создания сегмента всегда видна

- src/FiltrationConditionComponent/FiltrationConditionComponent.scss
> [RFC][issue-1028]Увожу мышку - схлопывается окно действий с фильтром

- src/FlatSelect/FlatSelect.scss
> [RFC][issue-975]Навести порядок в стилях `FlatSelect`

- src/HOOKs/useClickOutside/useClickOutside.tsx
https://github.com/mindbox-moscow/issues-dev2/issues/286
> Improved UseClickOutside HOOK's behaviour.

- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
https://github.com/mindbox-moscow/issues-devr/issues/670
> fix: segment expand button

- src/FiltrationGroupComponent/FiltrationGroupComponent.scss
- src/SegmentButtonExpand/SegmentButtonExpand.scss
https://github.com/mindbox-moscow/issues-devr/issues/670
> fix: expand button in active mode border
